field: bdd67a8b-0d17-49a2-97bc-f86f7e543c13 # Blind Draw Rounds
fieldLayouts:
  b451ebe9-0a4b-46cd-af9b-06412dfedae3:
    tabs:
      -
        elements:
          -
            fieldUid: 5c94933e-5413-4c0f-8782-cee0e955cf08 # Games
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5c94933e-5413-4c0f-8782-cee0e955cf08: # Games
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: games
    instructions: ''
    name: Games
    searchable: true
    settings:
      contentTable: '{{%stc_games}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a game'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: round
name: Round
sortOrder: 1
