fieldLayouts:
  190985fb-4d05-4986-a0bd-65352912db15:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: af3615af-c06f-4804-b179-040281bb1151
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6fcf820f-5057-4f40-996a-bf82db739663
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: dd191238-04e4-486e-9029-d27780b2ce11
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 22337b3e-aad9-4fa1-9db9-7bf2b4eb7156
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bdd67a8b-0d17-49a2-97bc-f86f7e543c13
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 608f1f15-eead-4798-9900-48ee61e4e4f2
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Settings
        sortOrder: 1
handle: competition
hasTitleField: true
name: Competition
section: 1603eea6-0c0e-4863-92c8-a25ff80c277a
sortOrder: 2
titleFormat: ''
