fieldLayouts:
  a1fdba88-fd27-4e25-94cd-21262a50ef6e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5ed8169f-c2f7-4274-b3df-5cff9230b7b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e98bd9b-16c1-4297-8be8-f06faf29e166 # Player 1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1526948-9de0-4172-a4b1-430720f875ba
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bee18029-c323-4668-8fc5-25beeb03a0e8 # Player 2
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1926d72-00ea-4973-a20d-cc258e08061e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0900cd97-c6b2-4a38-b2a0-0704a2955d60 # Player 1 Legs Won
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1bf1f6-0f8d-4bb8-a0b1-5c4226121875
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 01708089-e9c5-4433-ae94-ac087bad598c # Player 2 Legs Won
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd3aa05e-1b24-436d-824c-d3ae80f672c5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6fcf820f-5057-4f40-996a-bf82db739663 # Special information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbd02eca-c659-4c98-9ba4-955068887e7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 022f1b02-5045-493c-8ea3-47f05eecf73f # High Checkouts (100+)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30419d2e-df13-4f48-8b20-a558e4d18a87
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 22676616-9ffa-4539-834c-4f5730c47cf8 # High Scores (140+)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57218899-8993-4dbe-9204-3cd6bd48718d
            userCondition: null
            warning: null
            width: 50
        name: Common
        uid: c0a76219-d040-4130-8063-e2dea886fdf6
        userCondition: null
handle: games
hasTitleField: false
name: Games
section: 1603eea6-0c0e-4863-92c8-a25ff80c277a # Games
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{ player1.one().title } vs { player2.one().title }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
