columnSuffix: null
contentColumnType: string
handle: blindDrawRounds
instructions: 'Add the games for each round as drawn in the blind draw.'
name: 'Blind Draw Rounds'
searchable: false
settings:
  entryTypes:
    -
      uid: 1c91957f-362f-41f4-8645-e9766e9c8dce
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
