columnSuffix: null
contentColumnType: boolean
handle: blindDrawForEachRound
instructions: 'To automatically generate the whole tournament draw leave this turned off. If games are drawn between rounds, turn this on.'
name: 'Blind Draw for each round?'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
