columnSuffix: null
handle: checkout
instructions: null
name: 'High Checkouts (100+) - Checkout'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: 170
  min: 100
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
