columnSuffix: null
contentColumnType: string
handle: competitionType
instructions: null
name: 'Competition Type'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 'Round Robin'
        -
          - value
          - roundRobin
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Elimination
        -
          - value
          - elimination
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Winner Stays On'
        -
          - value
          - winnerStaysOn
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
