columnSuffix: null
handle: games
instructions: null
name: 'Blind Draw Rounds - Round - Games'
searchable: true
settings:
  contentTable: ''
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 825cfde3-de72-4c59-aaed-18d031db136f # Blind Draw Rounds - Round - Games Block
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
