columnSuffix: null
handle: highCheckouts
instructions: null
name: 'High Checkouts (100+)'
searchable: false
settings:
  contentTable: ''
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c3bd5d5d-f30a-4332-8474-2bdc340ef31b # High Checkouts (100+) Block
        -
          - group
          - General
  includeTableView: false
  maxEntries: 3
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
