columnSuffix: null
contentColumnType: string
fieldGroup: 741963c9-a9f3-46a4-b3cf-b5325fefb762 # Common
handle: highCheckouts
instructions: ''
name: 'High Checkouts (100+)'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 76adb1f2-9c15-4a0a-a5fc-bd9a32470c26 # Player
        -
          __assoc__:
            -
              - width
              - ''
      -
        - f7e93046-8f41-412f-abd5-89ca673abce7 # Checkout
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_highcheckouts}}'
  fieldLayout: row
  maxRows: '3'
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a high checkout'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
