columnSuffix: null
handle: player3
instructions: null
name: 'High Scores (140+) - Player'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Choose player'
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:5aa6b3a0-9cda-48d1-a96d-136848c948a4' # Players
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
