columnSuffix: null
contentColumnType: integer(10)
handle: player2LegsWon
instructions: null
name: 'Player 2 Legs Won'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
