columnSuffix: null
contentColumnType: string
handle: players
instructions: null
name: Players
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add players'
  showSiteMenu: true
  sources:
    - 'section:5aa6b3a0-9cda-48d1-a96d-136848c948a4' # Players
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
