columnSuffix: null
handle: score
instructions: null
name: 'High Scores (140+) - Score'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 180
  min: 140
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
