field: 5c94933e-5413-4c0f-8782-cee0e955cf08 # Games
fieldLayouts:
  ac3bf22b-b7e5-478a-ac6f-f15242aa197e:
    tabs:
      -
        elements:
          -
            fieldUid: 48ac97fc-80b3-4ad2-a9a4-30e09934a0ac # Player 1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a44bb3c5-38ba-495a-90d8-ccbf246f319d # Player 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  48ac97fc-80b3-4ad2-a9a4-30e09934a0ac: # Player 1
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: player1
    instructions: ''
    name: 'Player 1'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Choose player 1'
      showSiteMenu: true
      source: null
      sources:
        - 'section:5aa6b3a0-9cda-48d1-a96d-136848c948a4' # Players
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a44bb3c5-38ba-495a-90d8-ccbf246f319d: # Player 2
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: player2
    instructions: 'Leave blank if player 1 gets a bye.'
    name: 'Player 2'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Choose player 2'
      showSiteMenu: true
      source: null
      sources:
        - 'section:5aa6b3a0-9cda-48d1-a96d-136848c948a4' # Players
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
