field: bdd67a8b-0d17-49a2-97bc-f86f7e543c13
fieldLayouts:
  926069a6-ccb3-4017-bdd6-d6d67b9eb1a5:
    tabs:
      -
        fields:
          c758c904-71cc-4f44-a7ff-6ac8576b6724:
            required: '0'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  c758c904-71cc-4f44-a7ff-6ac8576b6724:
    contentColumnType: text
    fieldGroup: null
    handle: games
    instructions: ''
    name: Games
    searchable: '1'
    settings:
      addRowLabel: 'Add a game'
      columnType: text
      columns:
        col1:
          handle: player1
          heading: 'Player 1'
          type: singleline
          width: ''
        col2:
          handle: player2
          heading: 'Player 2'
          type: time
          width: ''
        col4:
          handle: player1GetsABye
          heading: 'Player 1 gets a bye?'
          type: lightswitch
          width: 120px
      defaults:
        -
          col1: ''
          col2: null
          col4: ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
